### ISSUE TITLE
Compatibility with metric system

### ISSUE THREAD

**Issue by mech-tools** [VanirDev/VariantEncumbrance#11]
Hello,

Can you add compatibility with the metric system for movement reduction by adding values in the settings, so we can define movement reduction ourselves?

Thx!

**Comment by VanirDev** [comment]
Absolutely, I'll add in some settings for this 👍

**Comment by mech-tools** [comment]
Hey, any news on that setting? 😄

**Comment by VanirDev** [comment]
Added support for custom speed decrease values in the settings, and added a setting for custom unit strings to be displayed above the encumbrance bar. https://github.com/VanirDev/VariantEncumbrance/commit/bbcc060da806ce51b948e3a7b720b4c8fd444fac
