### ISSUE TITLE
Compatibility with Inventory+ mod

### ISSUE THREAD

**Issue by drdwing** [VanirDev/VariantEncumbrance#12]
Hi,

Variant Encumbrance mod is broken while using with inventory+ mod..

I'm so sad..😢

**Comment by VanirDev** [comment]
Variant Encumbrance has undergone a sizeable refactor in the new version 0.2
I've just tested it, and it seems that Inventory+ works, although intrinsic weight of a category is not currently included in the weight calculations. The weight of items in the category seems to be calculated fine. I'll add it to my to-do list!

**Comment by geoidesic** [comment]
There's a problem with the "ignore weight" option for a category from inventory+. If this module is installed then that setting is ignored.
