### ISSUE TITLE
Add compatibility for the new speed system in 5e

### ISSUE THREAD

**Issue by Ikabodo** [VanirDev/VariantEncumbrance#13]
There has been update on how 5e handles speed in foundry. This module should update to account for that. :)

The old attribute is
- data.attributes.speed

The new attributes are:

- data.attributes.movement.walk
- data.attributes.movement.burrow
- data.attributes.movement.climb
- data.attributes.movement.fly
- data.attributes.movement.swim
- ~~data.attributes.movement.units~~

**Comment by VanirDev** [comment]
With the new Active Effects-based system used in Variant Encumbrance v0.2, these new attributes are now being used.
