### ISSUE TITLE
Issue with VTT 0.7.7

### ISSUE THREAD

**Issue by dsorrentino** [VanirDev/VariantEncumbrance#14]
When I have this module enabled in 0.7.7, randomly players and GM will lose the ability to access their character sheets.  The sheet will come up but clicking Inventory or trying to change anything doesn't work.  I am using the Default 5e Character Sheet.  Let me know if there's any debug data I can provide to help locate the issue.

**Comment by VanirDev** [comment]
Thanks, I believe this will probably be an issue with some new changes to 5e's speed system. I'll be releasing a 0.7.7 compatible release shortly!

**Comment by VanirDev** [comment]
I've just released a major update to Variant Encumbrance. If you could try updating and see if you can reproduce this issue, that'd be great! If the issue is persisting, I'd love to get a list of your modules and whatever steps you can provide to reproduce it myself.

**Comment by VanirDev** [comment]
No feedback or response, issue is closed for now.
