### ISSUE TITLE
Darker Dungeon Inventory Slot System Support

### ISSUE THREAD

**Issue by w1face** [VanirDev/VariantEncumbrance#2]
Hi!  Looking great so far!

Is there anyway to use further homebrew rules?  For example the Inventory Slot system introduced in Darker Dungeons?

**Comment by VanirDev** [comment]
At the moment there isn't any built in way to change the logic used from the standard weights to a slot based system. 

I could rework the logic used for calculating maximum carry to instead be based on creature size and strength modifiers as Darker Dungeons would need. The easiest way to do this would be to use the existing weight system, but have 1 unit be equivalent to 1 slot, so you'd have to manually set your items to have weight values to match this.

I've already implemented multipliers for equipped items, so you could easily use those to remove the slot cost for items when worn, although I'd need to write in an exception to this for armour.

Magical containers in Darker Dungeons would be a smidge more difficult, although the most obvious solution to that would be to give negative weights to those, and then any items with negative weight will add to the maximum slot count. Making item-specific solutions isn't something I'm too eager to do, so cases like the portable hole where it occupies 1 slot while folded, and then changes to a slot increase of +18 when unfolded, might have to just be something you manage with a Macro.

I'll look into it, and I may push this into a future version!

**Comment by w1face** [comment]
There are other modules that create containers that always weigh the same,
regardless of what's in them... so that could be a way?

**Comment by VanirDev** [comment]
Yep, that'd also do the trick! I'll have a play around, implementing changes to how max carry weight is calculated is pretty trivial. At the moment I can't really apply the disadvantages to checks that would be needed when you get over-encumbered, but I've seen mention of a better integrated conditions system in an upcoming version of Foundry, so that could be something to look into.

**Comment by w1face** [comment]
Cool!  I can't code worth a damn... but if you need any legwork or data entry to be done... then let me know! :)

**Comment by VanirDev** [comment]
Shelved for lack of demand.
