### ISSUE TITLE
User lacks permission to update Actor onUpdate

### ISSUE THREAD

**Issue by Drakynn** [VanirDev/VariantEncumbrance#20]
Environment:   Foundry VTT 0.7.9
Dnd 5e:  1.2.0

When a user updates their inventory, other players are seeing a popup message stating they lack permission to update Actor.

Tonight I had four players.  For the logs shown here, one user added an inventory item from the compendium.  They did not see any error.  The other three players all saw an error at the same instant.

```
{"level":"error","timestamp":"2021-01-03 21:28:22","message":"User Mazi lacks permission to update Actor CyUMiEErdVy1M49k","stack":"Error: User Mazi lacks permission to update Actor CyUMiEErdVy1M49k\n    at Function._onUpdate (/var/games/FoundryVTT/foundrycore/resources/app/dist/database/odm/document.js:1:8099)\n    at async Socket.handleEvent (/var/games/FoundryVTT/foundrycore/resources/app/dist/sockets.js:1:2262)"}
{"level":"error","timestamp":"2021-01-03 21:28:22","message":"User Tuesday lacks permission to update Actor CyUMiEErdVy1M49k","stack":"Error: User Tuesday lacks permission to update Actor CyUMiEErdVy1M49k\n    at Function._onUpdate (/var/games/FoundryVTT/foundrycore/resources/app/dist/database/odm/document.js:1:8099)\n    at async Socket.handleEvent (/var/games/FoundryVTT/foundrycore/resources/app/dist/sockets.js:1:2262)"}
{"level":"error","timestamp":"2021-01-03 21:28:22","message":"User Broche lacks permission to update Actor CyUMiEErdVy1M49k","stack":"Error: User Broche lacks permission to update Actor CyUMiEErdVy1M49k\n    at Function._onUpdate (/var/games/FoundryVTT/foundrycore/resources/app/dist/database/odm/document.js:1:8099)\n    at async Socket.handleEvent (/var/games/FoundryVTT/foundrycore/resources/app/dist/sockets.js:1:2262)"}
```
Disabling VariantEncumbrance plugin stops the error messages so I believe the problem lies here.

This has been reported by myself, Ravenknight and others in the FoundryVTT Discord.

**Comment by VanirDev** [comment]
Known issue due to an oversight with how the effect system is implemented currently, I'm working on a fix but the holidays have been keeping me busy.

**Comment by Drakynn** [comment]
Here's what the devtools console looks like when a player drags a piece of armor to their inventory from the compendium.

Chrome user who added the item.

![armor_add_error](https://user-images.githubusercontent.com/76929992/104203030-aa0ef080-53f9-11eb-975b-a514c5cd4844.jpg)

The Firefox user who did nothing
![armor_add_error2](https://user-images.githubusercontent.com/76929992/104203044-aed3a480-53f9-11eb-92da-2822bc5167ec.jpg)

**Comment by VanirDev** [comment]
Yep, this is a known issue, it currently will happen with every inventory update for a character which others don't have ownership of. If you'd like to revert to the previous version which doesn't have active effects, you can download it here: https://github.com/VanirDev/VariantEncumbrance/releases/tag/v0.1.5

**Comment by Drakynn** [comment]
The current code as it exists in the repository as of this post does not solve the "User lacks permission to update" error which I've been seeing.

I manually pulled all of the modified files and I'm still seeing errors like this.  In this instance, a different user than the one named in the error message added an item to their inventory.  Same behaviour as originally reported above.

`
{"level":"error","timestamp":"2021-01-17 16:42:33","message":"User Hisoka lacks permission to update OwnedItems in parent 29i9QRQoUtSEDl1n","stack":"Error: User Hisoka lacks permission to update OwnedItems in parent 29i9QRQoUtSEDl1n\n    at Function._onUpdate (/var/games/FoundryVTT/foundrycore/resources/app/dist/database/odm/embedded.js:1:7985)"}
`

**Comment by VanirDev** [comment]
I have tested with multiple clients and permission configurations. I have not been able to reproduce this issue. Please update to the 0.3 version that is now available and provide me clear steps with how I can reproduce this issue. If I can't reproduce it, then i can't fix anything.
