### ISSUE TITLE
Can you add a Waight option in the effects area

### ISSUE THREAD

**Issue by Zarhog** [VanirDev/VariantEncumbrance#22]
I would like to be able to have items effect the waight value apon equip. 
![dasasdfaafa](https://user-images.githubusercontent.com/76391362/104341330-9646b580-54f1-11eb-9f85-1954698cda09.PNG)
can you please add an option to this section that will allow me to effect the waight value

**Comment by VanirDev** [comment]
Currently variant encumbrance does all weight calculations itself, and doesn't take into account any 3rd party effects. This will be improved in the future, but a workaround for now is to create an item in your inventory with a negative weight value to achieve the same affect as you seem to want.

**Comment by Zarhog** [comment]
> Currently variant encumbrance does all weight calculations itself, and doesn't take into account any 3rd party effects. This will be improved in the future, but a workaround for now is to create an item in your inventory with a negative weight value to achieve the same affect as you seem to want.

I would love to be able to do that, however our specific use case we are talking about 40+ people. which with the volume of users becomes hard to manage. it would be much nicer if you could add a field to the Effects section that allowes for the change of the waight value.

i understand the limitations and thank you for your reply

**Comment by VanirDev** [comment]
I'm tackling this today and will try to include this in the 0.3 release.

**Comment by VanirDev** [comment]
Effect support has been added with 0.3, for both add and multiply effects.
