### ISSUE TITLE
Follow-up

### ISSUE THREAD

**Issue by Zarhog** [VanirDev/VariantEncumbrance#24]
Hi its me again, sorry to bother you but, i cant find the option for "Atribute Waight" in the Effects section. 
![image_2021-01-18_054741](https://user-images.githubusercontent.com/76391362/104876972-ad9dfc80-5950-11eb-9510-bb6208c68a4f.png)

is it possible to add as i can see you have implemented support for it
if the correct effect is the "encumbrance" class then when i do Add -10 it spits back the Nan Value on waight and the same for + or multiply
<img width="589" alt="gsdgsdsdsd" src="https://user-images.githubusercontent.com/76391362/104877710-54cf6380-5952-11eb-96f9-a6a454e4b656.PNG">
<img width="499" alt="fasfasfasfas" src="https://user-images.githubusercontent.com/76391362/104877716-5862ea80-5952-11eb-8dd0-b5488df2870d.PNG">

**Comment by VanirDev** [comment]
I've released an update for an issue with inventory+ support which may have been interrupting the weight calculations, causing what you've seen here. You've got the correct attribute key for the weight, so it's likely that issue cropping up. Update the module in foundry, and make sure you're on the 0.3.1 version.
