### ISSUE TITLE
Issue with Inventory+

### ISSUE THREAD

**Issue by mech-tools** [VanirDev/VariantEncumbrance#26]
Hello,

It seems that this module doesn't read the option from Inventory+ for "non" custom categories.
In my game, if I enable "Ignore Item Weight" for categories like weapons, equipments and alike. This module still does add the weight of the items in the category to the global weight.

![image](https://user-images.githubusercontent.com/1687854/104966934-64968880-59e2-11eb-8bea-1146d26d171a.png)

**Comment by p4535992** [comment]
Should be fixed with 0.4.6
