### ISSUE TITLE
Strange stuff happening to attribute scores with active effects.

### ISSUE THREAD

**Issue by ExileofBrokenSky** [VanirDev/VariantEncumbrance#28]
Rather than retype everything, here's a discord link, starting from my post with the image of the observant feat:
https://discord.com/channels/170995199584108546/722566083499786352/803675789899071538

After running Find The Culprit, the issue only happens when Variant Encumbrance is active.

**Comment by p4535992** [comment]
Should be fixed with 0.4.6
