### ISSUE TITLE
When the settings "Heavily Enc. Strength Multiplier" is modified the bar color is not correctly setted

### ISSUE THREAD

**Issue by p4535992** [VanirDev/VariantEncumbrance#3]
**Environment Details:**

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.96
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome
Module Version: 

**Description of the issue:**
When the settings "Heavily Enc. Strength Multiplier" is modified the bar color is not correctly setted.

Steps to reproduce the issue:

1) Go to module settings.
2) Set the "Heavily Enc. Strength Multiplier" from "15" to "30"
3) Go to character sheet
4) The bar values seem to have some problem

Here some screenshot:

Default case with "Heavily Enc. Strength Multiplier" set to 15

![img1](https://i.imgur.com/FG6uwe2.png)

"Heavily Enc. Strength Multiplier" set to 30

![img2](https://i.imgur.com/iRuoWwy.png)

**Comment by VanirDev** [comment]
Looks as-intended to me. The weight of the character is within your heavy encumbrance range of 160 -> 480, therefore it's given the red hue.

The colour isn't based on how far the bar is full, but on what state of encumbrance you are in.

**Comment by p4535992** [comment]
OK, ty for the clarification
