### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Ikabodo** [VanirDev/VariantEncumbrance#33]
I noticed that this mod causes some (probably unintended) performance issues, especially with a lot of other modules. It seems the sheet of characters is being updated a whole lot, and with some other modules this adds up. 

Removing this module sped up a lot of things for me. 

I'm not sure what is causing ut, but seems to have something to do with active affects and the encumberance causing the sheet to render to often.

**Comment by p4535992** [comment]
Partially fixed with 0.4.6 (unfortunately the calculation mechanism is triggered at each insertion, cancellation and update of any of the inventory objects it is difficult to make it performant in this sense, unless you have some idea)

**Comment by p4535992** [comment]
Update readme.md
