### ISSUE TITLE
Preparing a Spell reset Encumbrance.

### ISSUE THREAD

**Issue by Nauthul** [VanirDev/VariantEncumbrance#34]
Hello!

First of all, thank you very much for this wonderful module!
After doing some testing in a new world using only this module, I believe I have identified a bug, specifically when preparing/un-preparing spells.

### Issue:
Preparing a spell (and maybe other interactions) triggers a call to _updateEncumbrance_ with the spell data as the _updatedItem_ parameter and _mode_ set to _add_.
The spell data does not contain any weight info, but is added to the item list for weight anyway, later causing the _calculateEncumbrance_ function to always return an _encumbranceTier_  of 0 by introducing _NaN_ values during the process.

### Possible Fix:
Quick & Dirty I used for testing: on _VariantEncumbrance.js_ line 235, replace
`if (mode == "add") {` with `if (mode == "add" && !!updatedItem.data.weight) {`
Proper Fix: Check the validity of _updatedItem_, but I'm not sure what valid data should look like so...

**Comment by VanirDev** [comment]
Wow, that's a very interesting edge case! Thanks for the well reasoned explanation for this, it'll give me a good starting point. I imagine this will be a simple case of cancelling the update if the item doesn't have a valid weight as you've said.

**Comment by Nauthul** [comment]
After a little more testing, the `updateOwnedItem` hook seems to be called when interacting/moving/updating spells as well as feat/features, in addition to items. Both of which shouldn't have weight, so either checking for that or the `updatedItem.type` (either "feat" or "spell" from what I found) should do the trick nicely :)

I didn't find any more case of this but I only did some quick testing.

**Comment by p4535992** [comment]
Should be fixed with 0.4.6
