### ISSUE TITLE
Shows NaN after the latest 1.4.1 DnD5e update

### ISSUE THREAD

**Issue by giogreymon** [VanirDev/VariantEncumbrance#38]
![image](https://user-images.githubusercontent.com/77355668/127522602-dc161a19-dc93-4537-9b2e-cab0de78a25c.png)

**Comment by Nyogtha68** [comment]
Same.
![image](https://user-images.githubusercontent.com/88248539/127748082-abdf5ca4-a28a-407c-895e-642948426c8d.png)

**Comment by cvanhouten35** [comment]
Same here but it counts how much weight they are carrying but not in the bar. 
![image](https://user-images.githubusercontent.com/59463137/127787805-dacb1a5e-aa02-4270-b74e-da103b5080b7.png)

**Comment by p4535992** [comment]
Should be fixed with 0.4.6

**Comment by Nyogtha68** [comment]
Still the same for me unfrotunately.

**Comment by p4535992** [comment]
Exception too?

**Comment by Nyogtha68** [comment]
![image](https://user-images.githubusercontent.com/88248539/131129192-02ee1ea7-508a-47f9-8814-81836758ec83.png)

**Comment by p4535992** [comment]
Can you make a export of your character sheet and pass to me ?

**Comment by Nyogtha68** [comment]
It seems to have issues with the D&DBeyond character and the Compact D&DBeyond sheet mods.  OGL, Tidy and default sheets are showing proper encumberance.

**Comment by Nyogtha68** [comment]
> Can you make a export of your character sheet and pass to me ?

Emailed export of the character.

**Comment by p4535992** [comment]
A ok D&DBeyond character and the Compact D&DBeyond sheet mods are still in developing.

**Comment by p4535992** [comment]
D&DBeyond character and the Compact D&DBeyond partially work, no visual bar (because absent), but weight calculation and active effects seem to work
