### ISSUE TITLE
Can't install from Foundry

### ISSUE THREAD

**Issue by benbarbour** [VanirDev/VariantEncumbrance#40]
If I click the Install button in the Foundry module search box I get a red error popup.

![image](https://user-images.githubusercontent.com/487715/131729916-dd8cfdff-0aa4-42c5-b2ce-af389014a205.png)

**Comment by p4535992** [comment]
Fuck messed up the module.json, now should be fine.

**Comment by benbarbour** [comment]
Fixed, thanks!
