### ISSUE TITLE
(0.8.8) Error= Module variant-encumbrance-dnd5e is not allowed to call libWrapper with package_id='VariantEncumbrance'.

### ISSUE THREAD

**Issue by jocolamarco** [VanirDev/VariantEncumbrance#41]
![imagem](https://user-images.githubusercontent.com/45291719/131861784-34d8ab3c-505d-4d52-97c2-083d594b2f7a.png)

After enabling module and and applying changes.

FVTT 0.8.8
DND5e 1.4.2

**Comment by p4535992** [comment]
Try 0.5.3

**Comment by jocolamarco** [comment]
seems fixed in 0.5.3
