### ISSUE TITLE
Module eliminates calculation of coin weight

### ISSUE THREAD

**Issue by Dialectikal** [VanirDev/VariantEncumbrance#44]
### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Windows 10
* How Are You Using Foundry: Chrome
* Which Game System: dnd5e
* Modules Enabled?: yes [Inventory+, Item Containers, libWrapper, Variant Encumbrance]

### Issue Description

Regardless of other modules installed, this module eliminates the weight of any carried currency.

![VariantEncumbranceCoinBug1](https://user-images.githubusercontent.com/31572084/132775542-f7f206da-3498-4c3c-8052-87b96d0616b7.jpg)

![VariantEncumbranceCoinBug2](https://user-images.githubusercontent.com/31572084/132775559-560aed0e-4a46-41cc-8c4e-eed933e63111.jpg)

**Comment by p4535992** [comment]
Ty very much for this detailed ticket.
Should be fixed with 0.5.19.
Try it out.

**Comment by Dialectikal** [comment]
This issue appears to be fixed. Thanks!
