### ISSUE TITLE
"Powerful Build" Attribute not taken into account, incompatibility with Burger Time module

### ISSUE THREAD

**Issue by dczwardCZAR** [VanirDev/VariantEncumbrance#45]
* Foundry VTT Version: 0.8.9
* Operating System: MacOS 11.6
* How Are You Using Foundry: Native Application, Chrome
* Which Game System: dnd5e v1.4.3
* Modules Enabled?: yes

### Issue Description

I am using your mod, but when enabling the Special Trait --> Racial Trait --> Powerful Build, the character's carrying capacity is not changing -- it remains the same whether that box is checked or not. I have done enabling/disabling the mod, restarting FVTT, etc.

**Comment by p4535992** [comment]
Make sure to check the box of powerbuil on your character then

if you know how to check the values of your character with the code make sure that the data "data.flags.dnd5e.powerfulBuild" is "true" which is what is checked.

if you don't know how to do the check do a simple json export of the character (github does not accept json files rename it with ".txt" extension and attach it to your answer) so I do a check for you.

**Comment by dczwardCZAR** [comment]
Hello,

I have done those things…

    "dnd5e": {
      "savageAttacks": false,
      "halflingLucky": true,
      "weaponCriticalThreshold": 20,
      "initiativeHalfProf": false,
      "powerfulBuild": true
    },








—Douglas

**Comment by dczwardCZAR** [comment]
I figured it out! In the .json file, removed the flag for that “Burgertime” mod (which I no longer use), re-imported it, and now it looks correct…



Thank you for making this mod, i love it!

--Douglas

**Comment by p4535992** [comment]
Glad you solved it, I'll check if there is any incompatibility with the burger time module.
I'll let you know if i solved the issue.
