### ISSUE TITLE
Provide alternative weight trigger method

### ISSUE THREAD

**Issue by SR5060** [VanirDev/VariantEncumbrance#49]
I love the concept of the module, but I have tried using it for months now, and simply find the weight update triggers are incredibly touchy, often times my players will do something that causes 10-20 encumbrance triggers to occur and it turns into a mess. 

at least for me, the automation is simply not worth the effort and my players are not changing weight that much for it to be necessary. It would be great to be able to turn off the auto calulation and add a button on the sheet for those who want to manually trigger weight updates/encumbrance effects

**Comment by p4535992** [comment]
sorry to hear that, i made some performance on the automatizazion to try to avoid the multiple triggeration, but i also added a new feature if you want to disable the active effects integration [here](https://github.com/VanirDev/VariantEncumbrance#buttons-header-sheet-for-enabledisable-the-active-effect-actor-by-actor).

Some feedback is welcome.

**Comment by SR5060** [comment]
Thanks I'll take a look, at first glance it looks like it turns off the automation itself vs turning on/off the encumbrance, is that correct?

**Comment by p4535992** [comment]
it disable only the active effects feature , it had no sense for me to also disable the weight calculation otherwise you don't want to install this module, but use the Dfred Convenient effects module and add the AE by hand.

**Comment by SR5060** [comment]
Ah ok, it was coupling it with dfreds that I didn't think about. Yea that seems like a reasonable solution (in my mind I was thinking the button would add/remove the effect, similar to what dfreds does). I'll let you know if I have any additional feedback, thanks!
