### ISSUE TITLE
Feature Request: Add support for characters with Powerful Build trait/ which in turns requires size based calculations for carrying capacity.

### ISSUE THREAD

**Issue by ExileofBrokenSky** [VanirDev/VariantEncumbrance#5]
"Powerful Build. You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift."
Currently everything assumes a medium sized character. 
Each size category step increases or decreases (ignoring size Small) carrying capacity by a factor of 2. PHB p176: "Lifting and Carrying"
So just some simple math and a couple lines of code to look for creature size and if they have the powerful build trait flag in the character sheet's special traits.

**Comment by VanirDev** [comment]
Support has been added and is available in the 0,1,4 release!
