### ISSUE TITLE
BUG when combined with Magic Items module

### ISSUE THREAD

**Issue by GambetTV** [VanirDev/VariantEncumbrance#50]
When this module is combined with the "Magic Items" module and a limited number of charges is put on the spell attached to the item, and the item is set to destroy itself, an error message pops up that says the following:

Uncaught (in promise) Error: The key XgBGASnpUdEGFzOT does not exist in the EmbeddedCollection Collection
[No packages detected]
    at Map.get (/G:/FoundryVTT/resources/app/common/utils/collection.mjs:106)
    at ServerDatabaseBackend._updateEmbeddedDocuments (/G:/FoundryVTT/resources/app/dist/database/backend/server-backend.mjs:1)
    at ServerDatabaseBackend.update (/G:/FoundryVTT/resources/app/common/abstract/backend.mjs:153)
    at async Socket.handleEvent (/G:/FoundryVTT/resources/app/dist/server/sockets.mjs:1)

Disabling your mod fixes the issue.

**Comment by p4535992** [comment]
Can't replicate the error, can you pass me the actor you are using?

**Comment by Arcainne** [comment]
I'm having the same issue.
![image](https://user-images.githubusercontent.com/4230871/159114687-61174d9d-eabe-4986-b8d8-8de444e4c630.png)

The charges setting inside the Magic Item config doesn't seem to matter.
![image](https://user-images.githubusercontent.com/4230871/159114781-a8fcf80a-3750-4c5c-9bf2-8e8f88abb239.png)

**Comment by p4535992** [comment]
Can you export the json of the actor (and rename with txt extension so you can upload on github) ?It's more easy for me to replicate the use case.

**Comment by Arcainne** [comment]
Weird. Things seem to be working now... Not sure if restarting the server or something fixed things? Either way, here's the actor data.

[fvtt-Actor-cloevir.txt](https://github.com/VanirDev/VariantEncumbrance/files/8310654/fvtt-Actor-cloevir.txt)
