### ISSUE TITLE
Button to calculate the weight of items

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [VanirDev/VariantEncumbrance#51]
(Google Translator) I think it would be interesting to have a button on the sheet, a macro or something like that so that the sum of the weights would only be calculated when it was clicked. I say this because if all items are being calculated and any changes happen, it takes a few seconds for the update to occur.
So I think the calculation of items could and applications of dynamic effects could be paused until clicking the button.

**Comment by p4535992** [comment]
Added a new feature on 0.6.6, checkout the [readme](
https://github.com/VanirDev/VariantEncumbrance/tree/master#buttons-header-sheet-for-enabledisable-the-active-effect-actor-by-actor)

**Comment by CapivaraTupiniquim** [comment]
Just the way I thought, thanks! (Looks like the module weight calculation is faster than before, congratulations bro)
