### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kariaudhanaur** [VanirDev/VariantEncumbrance#52]
**Module Version:** v0.6.7

**Describe the bug**
(Description made by a non native english speaker :) )
AE not working

After the update yesterday, I went into the parameters, and put some numbers. It was working for some time...
After several clicks on the character sheet, the active effect dissappeared (speed reduction)... And it's impossible to put it back.

I tried today too, on a PC who was "slightly encumbered", made his weight "ok" for no malus, and added him some stuff to make him encumbered again.............. nothing ! 

![image](https://user-images.githubusercontent.com/92259502/142066241-15574aeb-306e-428f-8815-753c42c94ca5.png)
![image](https://user-images.githubusercontent.com/92259502/142066367-24454a74-23c1-4f1e-bffb-44657b9babbb.png)
![image](https://user-images.githubusercontent.com/92259502/142066427-1f40ae31-9245-499e-bed0-68467ec3cbc1.png)

Thanks for your mod anyway.

**Comment by p4535992** [comment]
Forgot a check, version 0.6.8 should be fix this. Ty for the issue. Let me know

**Comment by Kariaudhanaur** [comment]
That's perfect ! :) (need to unequip / equip to do some "refresh")
Thanks a lot !

**Comment by p4535992** [comment]
Yea i can't avoid the refresh sadly. Sorry about that. Cheers.
