### ISSUE TITLE
[BUG] Is calculating Vehicle Weight

### ISSUE THREAD

**Issue by flamewave000** [VanirDev/VariantEncumbrance#53]
**Module Version:** v0.6.8

**Describe the bug**
Vehicle weight is being calculated when it should not be.

**To Reproduce**
1. Create a Vehicle Actor
2. Set the vehicle's Cargo Capacity to 2 Short Tons
3. Observe the calculated weight now reads `N/4 lbs.`

**Expected behavior**
Should not be performing weight calculations for Vehicles.

**Screenshots**
Vanilla FoundryVTT
![image](https://user-images.githubusercontent.com/3588046/142706617-7827f2e8-1403-4562-820e-bbb5fa9d9094.png)

With Variant Encumbrance
![image](https://user-images.githubusercontent.com/3588046/142706642-35795141-2b08-4f62-9120-7d4ccb3ccc46.png)

**Browser:**
 - Brave

**Foundry Version:** 0.8.9

**Game System:** DnD5e 1.5.3

**Comment by p4535992** [comment]
With 0.6.9 I should have solved the problem on the vehicle character sheet, but if you didn't want to implement it I added a setting to specify the type of actor for which you want to activate the module in this case you have to change the value "character, vehicle "in" character ".
P.S. I tried to add an integration of your "Vehicle Cargo Capacity Unit" feature if you wanted to try it.

**Comment by flamewave000** [comment]
Thanks! Yeah it didn't make sense to me for vehicles since they don't have "Strength" to calculate a carry-weight, instead they just have a plain field for it. I don't mind the idea of encumbering a vehicle though, so long as it doesn't calculate it from Strength, but just just use the data field `data.attributes.capacity.cargo`.

Either way, I'll check it out and see how it looks :+1:

**Comment by flamewave000** [comment]
Sorry, I forgot to get back to this ticket. It all looks to be working well :+1:
