### ISSUE TITLE
[BUG] Max weight values now many times larger than they should be

### ISSUE THREAD

**Issue by Drakynn** [VanirDev/VariantEncumbrance#54]
**Module Version:** v0.6.9

**Describe the bug**
Since the last update all of the characters in my campaign have massive carrying capacity.   For example my Sorceror with a mere STR of 6 is reporting  28.2/1350 lbs.

**Foundry Version:  0.8.9** 

**Game System:  DnD 5e  1.5.5 **

**Comment by Arcainne** [comment]
Seeing the same issue.

**Comment by p4535992** [comment]
Set the settings "Enable or disable the strength multiplier feature" to false for avoid this issue i will look up on the next release

**Comment by Drakynn** [comment]
Definitely resolved with v0.6.10.

Thanks for the amazingly fast response!
