### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OldSociety** [VanirDev/VariantEncumbrance#55]
**Module Version:** v0.7.0

My players max weights are at randomly high numbers: 3300, 10,000, etc... The weight calculator otherwise works. If I delete the module, the weight scores fix themselves. But when I reinstall the bug comes right back exactly as it was - no matter how many times i delete it.

**To Reproduce**
I don't know how to reproduce the error, but it affects every single player character including new ones.

**Screenshots**

![Screenshot 2022-01-05 131433](https://user-images.githubusercontent.com/77307519/148296158-c38213d4-6a1a-409f-b5a7-e43bf7b737be.png)

 - 

**Foundry Version:** 
Bug happened v8.8 and carried over to 9.2

**Game System:** 
dnd5e

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
any exception on the web console ? 
pass me a exported json character for confirm some module uncompatibility with some flag from other modules.

**Comment by OldSociety** [comment]
The console seems clear to me. No errors at all.
[fvtt-Actor-ambrose-(etty).zip](https://github.com/VanirDev/VariantEncumbrance/files/7818191/fvtt-Actor-ambrose-.etty.zip)
[fvtt-Actor-etryn-(amber).zip](https://github.com/VanirDev/VariantEncumbrance/files/7818192/fvtt-Actor-etryn-.amber.zip)

**Comment by p4535992** [comment]
Tested with 0.8.9 and  9.238 and seem to work, must be some module collision, can you use the module https://foundryvtt.com/packages/forien-copy-environment and pass me the full setting of your game ?

**Comment by OldSociety** [comment]
[foundry-settings-export.zip](https://github.com/VanirDev/VariantEncumbrance/files/7818509/foundry-settings-export.zip)

How's that?

**Comment by p4535992** [comment]
@OldSociety the module settings are all set to 0 and false. I don't know why is happened, maybe during the update of the system or foundry or the world something go wrong ? The solution is reset the module setting to the default (the setting are on the world not the module this is why the instal/unistall method is not working). 
You can reset with foundry reset button or check the defaul values on the settings table at the bottom of the README file.

**Comment by OldSociety** [comment]
So I tried resetting the module to default (uninstalling all the other modules first except the required) and this is is the result. For now I'll just have to not use it, but if a fix is found, please don't hesitate to let me know. It's so strange. 

![Screenshot 2022-01-06 081704](https://user-images.githubusercontent.com/77307519/148414660-c1080664-7c44-4907-a9e7-a423bab8cd27.png)

**Comment by p4535992** [comment]
send me a screenshot of your module settings on this world

**Comment by OldSociety** [comment]
Sorry for the delay, I restored a backup from my Foundry and then after putting the settings back to default, it works. I really appreciate your help and your quick response!
