### ISSUE TITLE
[BUG] Throwing Errors When Used with Pop Out and Item Containers

### ISSUE THREAD

**Issue by Dialectikal** [VanirDev/VariantEncumbrance#56]
**Module Version:** v0.7.3

**Describe the bug**
While using the PopOut! module, and with an item container open, I receive an error when increasing and decreasing item quantity beyond encumbrance thresholds.

**To Reproduce**
1. Pop out character sheet
2. Edit container inside of character sheet
3. Add item to container
4. Increase item count until actor becomes encumbered
5. Reduce item count until no longer encumbered
6. Increase item count again
7. See error

**Expected behavior**
No error should be produced.

**Screenshots**
![image](https://user-images.githubusercontent.com/31572084/151483046-b84fef1b-c9f1-4d0c-b039-177729d4c6d0.png)

**Browser:**
Chrome

**Foundry Version:** 
0.9.245

**Game System:** 
DnD5e - Fifth Edition System - 1.5.7

**Additional context**
Only following modules are installed:
- Item Containers
- libWrapper
- socketlib
- Variant Encumbrance+Midi
- PopOut!

**Comment by p4535992** [comment]
Cannot replicate add some better check on 0.7.4 try out and let me know.

**Comment by Dialectikal** [comment]
I'm still seeing the error. I also notice that the encumbrance effect appears to get applied twice while the item is being edited in the inventory. This is ultimately corrected once the item window is closed, although it does cause quite a bit of lag.

**Comment by Dialectikal** [comment]
It looks like this error happens even without the PopOut! module. If I just increase the quantity of an item inside of a container on the character's inventory until overencumbered, and then decrease it back down, I get the error.

**Comment by p4535992** [comment]
Try this beta and let me know, sadly i rewite some code i didn't want to retouch.
`https://github.com/p4535992/VariantEncumbrance/releases/download/v0.7.5/module.json`

**Comment by Dialectikal** [comment]
It looks to be working correctly now. Thanks!
