### ISSUE TITLE
[BUG] Additional Error When Used with Pop Out and Item Containers

### ISSUE THREAD

**Issue by Dialectikal** [VanirDev/VariantEncumbrance#57]
Module Version: v0.7.3

Describe the bug
While using the PopOut! module, and with an item container open, I receive an error if I move an item from a popped out character sheet into the open item container.

To Reproduce

Pop out a character sheet
Add item to character sheet inventory
Open an item container
Move the item from the popped out character sheet to the open item container
See error

Expected behavior
No error should be produced.

Screenshots
![image](https://user-images.githubusercontent.com/31572084/151499040-c32e966d-553e-4033-aa1d-bbe1cafcc480.png)

Browser:
Chrome

Foundry Version:
0.9.245

Game System:
DnD5e - Fifth Edition System - 1.5.7

Additional context
Only following modules are installed:

Item Containers
libWrapper
socketlib
Variant Encumbrance+Midi
PopOut!

**Comment by p4535992** [comment]
Cannot replicate add some better check on 0.7.4 try out and let me know, but i see the error is on the tidysheet module rendering ?

**Comment by Dialectikal** [comment]
This error appears to have been resolved. I've tested moving items to and from inventory and containers and the error no longer pops up.
