### ISSUE TITLE
Encumbrance movement penalty is doubled when DAE is enabled

### ISSUE THREAD

**Issue by zag1024** [VanirDev/VariantEncumbrance#59]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

* Foundry VTT Version: 9.249
* Operating System: Red Hat Enterprise Linux (Host), Alpine Linux (Docker container)
* How Are You Using Foundry: Firefox
* Which Game System: dnd5e
* Modules Enabled?: yes, Variant Encumbrance, Item Containers and Dynamic Active Effects

### Issue Description

When Variant Encumbrance is configured to use speed penalties, the 10ft penalty is doubled while DAE is enabled, e.g. 30ft movement is reduced to 10ft when lightly encumbered.

**Comment by p4535992** [comment]
Totally missed that, try 0.7.8 and let me know.

**Comment by zag1024** [comment]
Yep, that seems to have worked - only seeing 10ft penalty for light encumbrance.
