### ISSUE TITLE
Not enabling encumbrance effect

### ISSUE THREAD

**Issue by Helm70** [VanirDev/VariantEncumbrance#60]
**Module Version:** v0.7.8

The encumbered effect doesn't change the speed of the token. Checking the effects finds that it has no content.

**Comment by p4535992** [comment]
Cannot replicate unless you can give me more info. If you use DAE make sure there isn't another active effect enabled on the actor.
Checkout for error with F12 on the browser.

**Comment by Helm70** [comment]
I've monitored the console while adding and removing weight from the tokens but no errors are noted. Tried deleting the encumbrance active effects to see if they were interfering with any module effects but this made no difference.

**Comment by p4535992** [comment]
_Tried deleting the encumbrance active effects to see if they were interfering with any module effects but this made no difference_ than must be some other active effect or module conflict. 
Can you pass to me the exported actor (json file) to confirm that ?

**Comment by Helm70** [comment]
I'll give that a go when I get home from work later. Thanks.

**Comment by Helm70** [comment]
Unsure how to send json files but hopefully this link will work:

https://drive.google.com/drive/folders/1ucw42szbNFj3oQe7Yt9RBVY7HNU-YTTa

**Comment by p4535992** [comment]
i found it a little bug with the new DAE release , try out the version 0.8.0 and let me know.

**Comment by Helm70** [comment]
Gave it a try this morning but sadly no improvement. I can't even see the previous "unencumbered" and "lightly encumbered" effects that I had seen before.

**Comment by p4535992** [comment]
tested again with the actor you share seem to work like it should. 

What did you mean by "unencumbered" and "lightly encumbered" effects ? The only active effects applied are "encumbered", "heavily encumbered", and "overburdened".

- "unencumbered" is not a active effect is a "fake effect" i use to tell to the module to remove the other active effect
- "lightly encumbered" is the name used on the module settings, but the active effect connected to that is "encumbered"

![img](https://raw.githubusercontent.com/VanirDev/VariantEncumbrance/master/wiki/tutorial_ve_2022.gif)

maybe some module conflict ?

**Comment by Helm70** [comment]
I tested it again with just Variant Encumbrance, DAE and Tidy5ESheet and I just can't get the token speed to reduce when they become encumbered. I see no encumbrance related effects on the character sheets, is it possible I have deleted them in my attempts to resolve and they haven't been recreated? 
Edit: I checked out my other world and the module works as intended. Is it possible I have screwed up the effects on the characters in the affected world?

**Comment by p4535992** [comment]
not sure about it, can be anything , this is a online world where i can do some debug ?

**Comment by Helm70** [comment]
The affected characters have none of the encumbrance effects on them. I just wondered if there was a way to reinitialise the module to recreate these effects?

**Comment by Helm70** [comment]
Further testing of the module has provided some insight. The module works fine with normal equipment but coins don't trigger the encumbrance effect. I've checked and my system is set to apply currency weights so i think the issue is with coins.

**Comment by p4535992** [comment]
The system setting "Apply Currency Weight" is checked ?

**Comment by Helm70** [comment]
Yes, I had to double check just to be sure. The encumbrance bar changes colour to orange etc when I add coins but the characters speed doesn't change. When I add items the module works fine.
