### ISSUE TITLE
[BUG] Possible conflict between Variant Encumbrance and DF Quality of Life

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [VanirDev/VariantEncumbrance#61]
**Module Version:** v0.8.4

**Describe the bug**
The Changelog and Conflicts module reports incompatibility between the Variant Encumbrance and DF Quality of Life. It makes several updates that this happens and the warning does not go away. Any settings I disable between them also do not remove the warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/67530921/156391097-9b307279-528a-4942-92e7-223ccb9f8cb9.png)

**Configs**
Foundry Virtual Tabletop: Version 9, 9.251
Game System: dnd5e, 1.5.7
Active Modules: 67
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1165)
Max Texture Size: 16384

Scene: 3000 x 3000 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 7

Actors: 120 | Items: 86 | Journal: 24 | Rollable Tables: 40 |
Playlists: 4 | Compendium Packs: 43 | Chat Messages: 0

**Comment by p4535992** [comment]
Sorry  is this a issue ? are you trying to remove that conflict ? is not a warning (yellow color) is just a info (blue color), you can just ignore that.

**Comment by CapivaraTupiniquim** [comment]
That's the warning, but you can close the problem if you find it necessary.

![image](https://user-images.githubusercontent.com/67530921/158018886-1f8df200-be0a-4408-803f-95b5d807f38b.png)
