### ISSUE TITLE
Bulk variant

### ISSUE THREAD

**Issue by Orionox** [VanirDev/VariantEncumbrance#62]
Would be great if we could also get a variant of this that included item bulk. So that player are limited on weight and bulk

**Comment by p4535992** [comment]
Sorry I'm more of a programmer than an expert in the rules of dnd could you be more specific about the behavior you would like?

**Comment by Orionox** [comment]
> Sorry I'm more of a programmer than an expert in the rules of dnd could you be more specific about the behavior you would like?

LoL, no problem. It's not really a DnD rule so much as a request for homebrew content. Basically, a second bar that measures item sizes. So think of something like a comforter for a bed, it's not very heavy 10-15 pounds at most, but it's bulky and hard to carry even if it doesn't weigh much. A large framed painting, an ornate mirror, an alchemy crafting table all of those are "light" but they can't really be carried with a player without impeding how they are able to fight. I just want a second bar to track this so I don't have to. A small character could only hold a "bulk" of like 20 while a medium could hold a bulk of 40 and a large could hold a bulk of 80. I don't know exactly what would be involved, but I'm guessing you'd also have to add the ability to define bulk on each item which is likely out of the purview of this mod, but I figure it's worth asking for.

**Comment by p4535992** [comment]
k i understand, is for you personal game or there is some pdf or documentation you found on the web i can use for set up some constant ?

**Comment by Orionox** [comment]
No specific documentation I work from. I usually allow a naked small character to hold 10 bulk with a longsword being 5 bulk. From there a naked medium creature would start at like 15 bulk and a naked large creature would be around 17 bulk.  Basic clothing improves bulk by 10, and then I work from there. Small items are 1-2 bulk, medium 3-5, large 6+. 

It's not an exact system right now, just something I have been working on recently that I thought would fit nicely with this module since they are in similar veins.

**Comment by Orionox** [comment]
> k i understand, is for you personal game or there is some pdf or documentation you found on the web i can use for set up some constant ?

This https://www.giffyglyph.com/darkerdungeons/grimoire/4.0.0/en/active_inventory.html would be a good baseline to work from if you wanted something a little more solid than what I provided. My homebrew is that I use this AND weight together.

**Comment by p4535992** [comment]
@Orionox finally made the release add a bunch of module settings, when i will find the time i will make some video.
Try out version 0.9.1 and let me know for any bug

**Comment by Orionox** [comment]
> @Orionox finally made the release add a bunch of module settings, when i will find the time i will make some video. Try out version 0.9.1 and let me know for any bug

i do not see how to add bulk to items manually(Found it). Also some of my player characters aren't getting the bulk bar.

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/171928706-0bb8c23a-f296-43ea-8c5f-ee8afdffd46d.PNG)

**Comment by Orionox** [comment]
the bulk icon at the top of the character sheet shows for both these players, but only one has the bar.

edit:  If I drag a duplicate of the token that isn't showing the bar onto the scene then the bar shows up. a refresh will amke the bar disappear though. I'm also getting this error whenever I open a character sheet. ![Capture](https://user-images.githubusercontent.com/20059838/171930954-0229e783-f247-42e2-a699-feb42f9b5a95.PNG)

**Comment by Orionox** [comment]
The bulk area also shows up inconsistently. Sometimes its "X/Y" and sometimes its "X/Y Bulk
![Capture](https://user-images.githubusercontent.com/20059838/171931803-5350ac4a-63da-4653-a5ac-ca9f50cbd33d.PNG)
"

**Comment by Orionox** [comment]
Other than those small issues, the system appears to be working fine.

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/171932241-e2213050-c4c9-4adb-aade-abee023dafe8.PNG)
Here's another error I get when changing the bulk value of an item.

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/171932963-a0f2b0c7-f9ac-4729-bbd3-db3d80253c6d.PNG)
This is the error I get when I change the bulk of a container item.

**Comment by Orionox** [comment]
Last thing I noticed, the module with or without bulk activated does not appear to be affecting movement speed or applying the encumbrance or over-encumbered active effect.

**Comment by Orionox** [comment]
sorry if the reports are overwhelming

**Comment by p4535992** [comment]
try out 0.9.2 and let me know it
