### ISSUE TITLE
Variant Encumbrance prevents me from adding items to inventory

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [VanirDev/VariantEncumbrance#65]
**Submitted By**: Ref Lansky#3878
**Feedback Type**: Bug
 
**Core:** 9.269
**System:** dnd5e v1.6.1
**Module Version:** variant-encumbrance-dnd5e v0.9.9
**Dependency Version:** libWrapper v1.12.7.0
**Dependency Version:** socketlib v1.0.10
 
**Description**:
Latest update prevents me from adding items either through quick insert or drag from compendium.  Disabling module restores capability<details>
<summary>Active Modules</summary>

5e-statblock-importer--v1.4.5;
ATL--v0.4.01;
ActiveAuras--v0.4.13;
Dynamic-Effects-SRD--v6.0.01;
EasyTable--v1.3.3;
NotYourTurn--v1.2.7;
SoundBoard--v1.5.3;
_CodeMirror--v5.58.3-fvtt4;
_chatcommands--v1.4.0;
_document-sheet-registrar--v1.0.0;
_mathjs--v7.5.1-fvtt2;
_sortablejs--v1.14.0-fvtt1;
about-time--v1.0.6;
acelib--v1.4.0;
actor-attribute-lists--v0.0.5;
advanced-macros--vv1.14.3;
advancedspelleffects--v0.9.5.6;
alternative-rotation--v2.1.2;
ambientdoors--v2.2.6;
ammo-tracker-fvtt--v0.2.3;
arbron-hp-bar--v2.1.2;
autoanimations--v3.2.91;
autocomplete-whisper--v0.3.4;
automated-evocations--v1.6.1;
better-rolltables--v1.8.95;
betternpcsheet5e--v0.10.1;
betterroofs--v1.5.5;
beyond20--v1.4.1;
blind-roll-skills--v0.8.2;
bug-reporter--v1.3.3;
burger-time--v0.2.0;
character-actions-list-5e--v5.0.2;
chat-images--v2.5.6;
chat-portrait--v0.7.4;
colorsettings--v2.8.4;
combat-carousel--v0.2.5;
combat-enhancements--v1.1.1;
combat-numbers--v1.2.1;
combat-utility-belt--v1.9.2;
compact-beyond-5e-sheet--v0.20.0;
compact-compendium-list--v0.0.6;
compendium-browser--v0.7.2;
compendium-folders--v2.4.6;
condition-automation--v3.0.2;
conditional-visibility--v0.6.15;
dae--v0.10.20;
danger-zone--v1.5.2;
ddb-importer--v2.9.56;
debug-report--v0.1.5;
deprecated-modules--v1.1.6;
df-chat-enhance--v4.0.0;
df-curvy-walls--v3.3.1;
df-qol--v1.7.3;
df-scene-enhance--v3.5.1;
df-settings-clarity--v3.2.1;
df-templates--v1.2.1;
dfreds-convenient-effects--v2.6.3;
dfreds-droppables--v1.4.2;
dfreds-effects-panel--v1.5.1;
dfreds-pocket-change--v3.2.1;
dice-calculator--v1.5.2;
dice-so-nice--v4.5.1;
dnd-ui--v9.269.2;
dnd5e-helpers--v4.1.3;
dndbeyond-npc-sheet--v1.3.6;
drag-ruler--v1.12.8;
dragupload--v2.1.1;
enhancedcombathud--v1.3.2;
environment-interaction--v1.0.1;
fa-dm-screen--v0.4.2;
faster-audio-preload--v0.1.01;
find-the-culprit--v1.4.0;
forien-copy-environment--v2.1.4;
forien-quest-log--v0.7.9;
forien-unidentified-items--v0.4.1;
foundry-filepicker-favorites--v1.2.2;
foundry_community_macros--v9.16;
foundry_community_tables--v9.3;
foundryvtt-mountup--v3.2.23;
foundryvtt-show-notes--v0.6;
foundryvtt-simple-calendar--vv1.3.75;
fvtt-syrin-control--v0.3.0;
fxmaster--v2.7.0;
give-item--v1.11.0;
gm-notes--v0.5.0;
gm-screen--v3.0.1;
healthEstimate--v28.0;
hey-wait--v0.6.3;
illandril-chat-enhancements--v1.2.4;
image-previewer--v0.9;
initiative-double-click--v1.5;
innocenti-openlock--v0.4.6;
item-piles--v1.4.8;
itemacro--v1.5.7;
itemcollection--v1.8.19;
jb2a_patreon--v0.4.4;
kandashis-bag-of-hoarding--v0.1.01;
kandashis-fluid-canvas--v0.3.0;
laptop-fix--v0.0.8;
lessfog--v0.9.1;
lib-df-buttons--v1.3.2;
lib-wrapper--v1.12.7.0;
lights-hud-ate--v0.11.28;
lootpopulatornpc5e--v0.3.1;
lootsheetnpc5e--v3.6.0;
lordudice--v0.34;
macro-folders--v1.3.1;
macroeditor--v1.1.2;
magicitems--v2.2.1;
merchantsheetnpc--v2.6.0;
midi-qol--v0.9.62;
midi-srd--v0.2.03;
minimal-ui--v1.4.24;
moar-folders--v1.1.1;
module-credits--v1.1.11;
monks-active-tiles--v1.0.84;
monks-enhanced-journal--v1.0.64;
monks-hotbar-expansion--v1.0.14;
monks-little-details--v1.0.54;
monks-player-settings--v1.0.4;
monks-scene-navigation--v1.0.23;
monks-tokenbar--v1.0.67;
monks-wall-enhancement--v1.0.9;
multilevel-tokens--v1.5.4;
my-shared-content--v1.0.0;
nice-more-dice--v1.1.0;
optional-rules-dnd5e--v0.4.2;
parallaxia--v0.4.0e;
party-inventory--v1.5;
party-overview--v2.12.6;
perfect-vision--v3.9.12;
pin-cushion--v1.5.0;
poi-teleport--v0.2.1;
pointer--v2.3.4;
polyglot--v1.7.40;
popout--v2.8;
popout-resizer--v1.4.2;
quick-insert--v2.6.1;
raise-my-hand--v1.3.5;
rarity-colors--v0.1.05;
rest-recovery--v1.2.10;
secret-journal--v0.1.0;
selectiveshow--v2.1;
sequencer--v2.1.7;
settings-extender--v1.2.0;
simplefog--v0.2.1;
smalltime--v1.14.2;
smart-doors--v1.3.3;
smip-compendium--v0.6.0;
socketlib--v1.0.10;
spellTemplateManager--v2.1.3;
splatter--v2.9.7;
split-journal--v1.2.0;
stairways--v0.8.7;
tagger--v1.3.5;
targetreacts--v2.0.0;
theripper-premium-hub--v0.4;
tidy-ui_game-settings--v0.1.31;
tidy5e-sheet--v0.5.32;
times-up--v0.8.32;
token-attacher--v4.4.5;
token-health--v0.5.5;
token-hud-wildcard--v1.6.0;
token-mold--v2.15.1;
token-tooltip-alt--v3.1.2;
token-z--v0.6.5;
tokenmagic--v0.5.4;
tokenmagic-automatic-wounds--v1.0.4;
vtta-tokenizer--v3.8.4;
warpgate--v1.13.6;
weather-control--v4.1.6;
wild-magic-surge-5e--v1.12.0;
zoom-pan-options--v1.7.2;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by R0TEAM** [comment]
additionaly bug - hard to equip inventory items (Armor/Weapon) - most times not work ... witout module , back to normal

**Comment by p4535992** [comment]
try out 0.9.10

**Comment by ref2335** [comment]
Issue still present.  Cannot add or remove items from inventory with VE enabled.

**Comment by p4535992** [comment]
tested again is working on my worlds, click f12 and check for any error on the web console. Export a actor with the problem and attach to this issue renaming the file with ".txt".

**Comment by R0TEAM** [comment]
have this error with F12 found ->
`3
VariantEncumbranceImpl.js:1133 Uncaught (in promise) ReferenceError: ignoreCurrency is not defined
[Detected 4 packages: variant-encumbrance-dnd5e, lib-wrapper, itemcollection, system:dnd5e]
    at calcItemWeight (modules/variant-encu…mbranceImpl.js:1133)
    at calcWeight (modules/variant-encu…mbranceImpl.js:1115)
    at modules/variant-encu…umbranceImpl.js:355
    at Array.reduce (<anonymous>)
    at Object.calculateEncumbrance (modules/variant-encu…umbranceImpl.js:324)
    at Object._updateEncumbranceInternal (modules/variant-encu…umbranceImpl.js:100)
    at Object.updateEncumbrance (modules/variant-encu…cumbranceImpl.js:16)
    at Function.updateDocuments (modules/variant-encu…dule/modules.js:554)
    at Wrapper.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1)
    at Function.🎁CONFIG.Item.documentClass.updateDocuments#0 (modules/lib-wrapper/lib-wrapper.js:1)
    at Item5e.update (common/abstract/document.mjs:456)
    at Wrapper.🎁call_wrapped [as call_wrapped] (modules/lib-wrapper/lib-wrapper.js:1)
    at Item5e._update (modules/itemcollecti…temContainer.js:151)
    at Wrapper.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1)
    at Item5e.🎁CONFIG.Item.documentClass.prototype.update#0 (modules/lib-wrapper/lib-wrapper.js:1)
    at ActorSheet5eCharacter._onToggleItem (systems/dnd5e/module…ts/character.js:301)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)`

hope it helps - still no equiping or adding Items possible with the module

**Comment by p4535992** [comment]
@R0TEAM try out 0.9.11

**Comment by R0TEAM** [comment]
o.k. - work now again on my end ... equiping and add items now work ;)   . Thanks
