### ISSUE TITLE
[Request] Increasing carry weight on single actor isn't possible, could there be a % based system?

### ISSUE THREAD

**Issue by SLinxTheFox** [VanirDev/VariantEncumbrance#66]
Right now if you increase an actor's carry weight with an effect or what not the capacity doesn't adjust because it's manually set in the module settings.

It'd be cool if there was a setting to make each threshold for variant encumbrance percentage based, so it takes the default 5e weight and then you could type like 33% and 66%

Perhaps if you wanted the overall encumbrance higher or lower there could be a multiplier field for that
EX: take your current carry cap and multiply it by whatever you type in (like 1.15 or 0.9 or whatever), of course it'd need to not hard set the encumbrance as to allow effects and such to change the weight

Edited: second "threshold" to "percentage"

**Comment by p4535992** [comment]
@SLinxTheFox can you pass to me the actor with the DAE active effect for test purpose

**Comment by SLinxTheFox** [comment]
[fvtt-Actor-class-tester.zip](https://github.com/VanirDev/VariantEncumbrance/files/9274742/fvtt-Actor-class-tester.zip)
sure here ya go

**Comment by p4535992** [comment]
Try out v0.10.1. Let me know if the automatic calculation based on the DAE effect is enough or if you still need  to set manually the % of the thresholds (or if you find some bug).

**Comment by SLinxTheFox** [comment]
Right now it looks like it sets every encumbrance level 50 higher rather than the maximum that much higher and each other a percentage of that much higher.

also for some reason just some of my actor's encumbrance won't change with more or less items and always shows green
https://i.imgur.com/rTNNcFZ.png

I think, unless the DAE weight thing can do it's own calculation to raise all the other levels of encumbrance proportionately, then the percentage option is probably still the best.

Thanks for responding and taking time to work on this by the way! I super appreciate it!

**Comment by p4535992** [comment]
_Right now it looks like it sets every encumbrance level 50 higher rather than the maximum that much higher and each other a percentage of that much higher._
My bad... try out 0.10.2
_also for some reason just some of my actor's encumbrance won't change with more or less items and always shows green_
Can you export one of these actor ?

**Comment by SLinxTheFox** [comment]
Oh! it works perfectly! also i'm so sorry i got very distracted and got really sick, i totally forgot about this thread. 

Thanks so much for adding this just because of my request, and being so quick with it! I really do appreciate it a lot.

Here's an export
[fvtt-Actor-class-tester.zip](https://github.com/VanirDev/VariantEncumbrance/files/9388292/fvtt-Actor-class-tester.zip)

**Comment by p4535992** [comment]
No worrie is a game ^^

**Comment by p4535992** [comment]
Seem to work with the class-tester.
