### ISSUE TITLE
Encumbrance calculating different for DM and PC

### ISSUE THREAD

**Issue by Quixion** [VanirDev/VariantEncumbrance#76]
I have been using the "data.attributes.encumbrance.max" flag to grant PCs a little extra carry weight. I noticed that when the players alter their inventory, they're getting encumbrance effects applied sometimes, which does not happen when I alter their inventory. What it looks like is happening is that the encumbrance maxes are displayed and calculated properly for the DM but the PCs see and experience the old values. 

![image](https://user-images.githubusercontent.com/59381562/208674211-20be2433-89d7-4d16-91d0-c357fa0df165.png)
![image](https://user-images.githubusercontent.com/59381562/208674262-93ef5ae1-ef5e-4025-93c6-a97a0b8721e3.png)

When I add a little weight as the DM it appears to me that all is well but the players see themselves in the orange. 

![image](https://user-images.githubusercontent.com/59381562/208674507-1a7c8776-e014-442a-8934-564e09d9af8a.png)
![image](https://user-images.githubusercontent.com/59381562/208674551-861c6c56-6fb5-431c-b620-d9320c15e967.png)

The weird part is that if *I* am the one who changes something on the sheet that puts them overweight, nothing happens. If *they* are the ones that do it it triggers the status effects.

**Comment by p4535992** [comment]
Ticket is transfer here: https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/issues/8

Are you on 9 or 10 ?

If you are on 10: Don't use `data.attributes.encumbrance.max` use instead `system.attributes.encumbrance.max`

Export the actor for let me check the use case on my local machine, i tested with some actor, but can't replicate the issue.
