### ISSUE TITLE
Changed sheet breaks updates

### ISSUE THREAD

**Issue by crymic** [VanirDev/VariantEncumbrance#8]
Hi,

Just wanted to let you know if the sheet is changed to another one. It will no longer pick up weight changes.
Example click on or off weightless in backpacks.

**Comment by VanirDev** [comment]
Sorry, I'm not able to reproduce this bug. Would you mind giving me more details about what character sheets and other modules you are using?

**Comment by crymic** [comment]
Any sheet, default 5e or tidy
On 98 5e and 7.5.

**Comment by VanirDev** [comment]
I'm going to need more specifics about your process to get this error. I've tested on foundry 0.7.5 and 5e 0.98 with the latest tidy5e, default and alt5e sheets. I released an update to VariantEncumbrance last night. If you could update the plugin and tell me the exact steps you use to encounter the bug, I can have a shot at fixing it. Unfortunately I can't fix a bug I can't find.

**Comment by VanirDev** [comment]
Closed for inactivity.
